name: Branch build

on:
  push:
    branches:
      - "*"
      - "!main"
      - "![0-9].[0-9]"
  workflow_dispatch:

permissions:
  contents: read #  to fetch code (actions/checkout)
  checks: write #  to create new checks (coverallsapp/github-action)

jobs:
  stop-build:
    name: Check if build should be stopped
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.stop-build.outputs.result }}
    steps:
      - name: Check if there is an open PR for this branch
        id: stop-build
        uses: actions/github-script@v8
        env:
          ORGANIZATION: mixxxdj
          REPOSITORY: mixxx
        with:
          script: |
            try {
              const branch = context.ref.replace('refs/heads/', '');
              const { data: pullRequests } = await github.rest.pulls.list({
                owner: process.env.ORGANIZATION,
                repo: process.env.REPOSITORY,
                head: `${context.repo.owner}:${branch}`,
                state: 'open'
              });
              console.log(`There is ${pullRequests.length} PR open upstream for branch '${context.repo.owner}:${branch}'`);
              return pullRequests.length != 0;
            } catch (error) {
              console.log(`Didn't find a PR for branch '${context.repo.owner}:${branch}' on '${process.env.ORGANIZATION}/${process.env.REPOSITORY}'.`);
              return false;
            }

  pre-commit:
    if: needs.stop-build.outputs.result == 'false'
    needs:
      - stop-build
    uses: ./.github/workflows/pre-commit.yml
    with:
      pull_request: false

  checks:
    if: needs.stop-build.outputs.result == 'false'
    needs:
      - stop-build
    uses: ./.github/workflows/checks.yml

  build:
    if: needs.stop-build.outputs.result == 'false'
    needs:
      - stop-build
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.head_ref || github.ref_name }}
      ref: ${{ github.ref }}
