name: Docker

on:
  push:
    branches: ["main"]

  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize
      - labeled

permissions:
  contents: read
  packages: write

jobs:
  devcontainer:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'mixxxdj/mixxx' || contains(github.event.pull_request.labels.*.name, 'dev container') }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: .devcontainer/Dockerfile
          platforms: linux/arm64,linux/amd64
          pull: true
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'mixxxdj/mixxx' }}
          tags: ghcr.io/mixxxdj/mixxx/devcontainer:latest
