# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
#
# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    # if: ${{ github.event.repository.owner != 'mixxxdj' }}
    if: ${{ github.event.repository.owner != 'acolombier' }}
    steps:
      # - name: Generate App Token
      #   id: generate-token-key-pair
      #   uses: actions/create-github-app-token@v1
      #   with:
      #     private-key: ${{ secrets.MIXXX_BOT_APP_PRIVATE_KEY }}
      #     app-id: ${{ vars.MIXXX_BOT_APP_ID }}
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.TEST_PAT }}
          sync-labels: false
