name: Pull request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
  workflow_dispatch:

permissions:
  contents: read #  to fetch code (actions/checkout)
  checks: write #  to create new checks (coverallsapp/github-action)

jobs:
  pre-commit:
    if: needs.stop-build.outputs.result == 'false'
    needs:
      - stop-build
    uses: ./.github/workflows/pre-commit.yml
    with:
      pull_request: true

  checks:
    needs:
      - stop-build
    uses: ./.github/workflows/checks.yml

  git:
    uses: ./.github/workflows/git.yml

  build:
    needs:
      - stop-build
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.head_ref || github.ref_name }}
      ref: ${{ github.ref }}

  # This task is used as a probe for auto merge
  # In the future, it could also be used to perform a status update (e.g once the whole CI is passing + is ready for review, add a specific label such as `need review`)
  ready:
    name: Ready to merge
    needs:
      - pre-commit
      - checks
      - git
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Ready to go
        run: "exit 0"
